[package]
name = "aoc24-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
nalgebra = "0.33.2"
regex = "1.11.1"
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["full"] }

[profile.dev]
debug = "full"

[profile.release]
debug = "full"
